#version 460
#extension GL_EXT_ray_query : require

layout(set = 0, binding = 5) uniform accelerationStructureEXT acceleration_structures[];

layout(local_size_x = 1) in;

void main() {
    rayQueryEXT query;
    rayQueryInitializeEXT(
        query,
        acceleration_structures[0],
        gl_RayFlagsOpaqueEXT,
        0xFF,
        vec3(0.0),
        0.0,
        vec3(0.0, 0.0, 1.0),
        1.0
    );
}
